name: ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Emscripten SDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Setup Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Install npm dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Verify dist output
        run: npm run verify:dist
